### ISSUE TITLE
Upsample layer vs. convTranspose2d

### ISSUE THREAD

**Issue by youngwanLEE** [jvanvugt/pytorch-unet#1]
Did you compare the results between upsample layer vs. convTransposed2d?

**Comment by jvanvugt** [comment]
I don't have any numbers to show you, but I have empirically found the difference to be very small. I would thus recommend to use upsampling by default, since it doesn't have any parameters.

**Comment by jvanvugt** [comment]
I have written a short discussion on this issue (but no quantitative results)
https://github.com/jvanvugt/pytorch-unet/blob/master/README.md#discussion-of-parametersarchitecture
