### ISSUE TITLE
Pooling: avg vs max

### ISSUE THREAD

**Issue by fepegar** [jvanvugt/pytorch-unet#3]
I think the original paper uses max pooling layers, but this implementations uses average pooling. Is that correct?

**Comment by jvanvugt** [comment]
You are right, that is an oversight on my part. I don't know why I was doing average pooling there, so I have changed it to max pooling. Thanks a lot!

**Comment by fepegar** [comment]
No worries! Btw [I adapted it](https://github.com/fepegar/pytorch-tests/blob/master/examples/segment/unet_github.py) to be used in 3D as in [3D U-Net: Learning Dense Volumetric Segmentation from Sparse Annotation](https://arxiv.org/abs/1606.06650). I can create a PR here if you want :)
