### ISSUE TITLE
Pre trained unet

### ISSUE THREAD

**Issue by vpapaioannou** [jvanvugt/pytorch-unet#6]
As far as I understand, the provided U - net is not trained. How could it be possible to have a pre - trained U - net. Is there a way to load any available weights? Also, since U - net works well with small training data sets, does it make sense to have a pre - trained U - net? I say this, because, if the input image is large enough, then it can be split in many patches - images available for training. Finally, can PyTorch run directly a Caffe2 network e.g. through onnx-caffe2 module?

Thanks.

**Comment by jvanvugt** [comment]
The code in this repository implements the U-net model, you will have to train it on your own dataset. Of course, if you want to pretrain it on a different dataset you can do that and save and load the weights as described in this tutorial https://pytorch.org/tutorials/beginner/saving_loading_models.html.

I don't have any experience with Caffe2, so I can't you help you there unfortunately.
